name: slfc
favicon: null
layout_spectrum: 0.2911897269077599
typography_spectrum: 0.8763671172782779
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7715072331484407
  lightness: 0.8571482342667878
  saturation: 0.8662018957547843
  rhythmicContrast: 0.23263082630001009
purpose: []
